pages/about.jsx, pages/expect.jsx
A better version of PR #166.  This one doesn't have the weird whitespace differences.
This fixes #157
=> Copy changes (a better version of PR #166)

pages/location.jsx
=> Fixed typo in address

components/header.jsx, pages/home.jsx
This fixes #184 
@ScottDowne another one for you to review :+1:
=> Updated homepage CTA and nav bar

app.js
I should've removed this when we stopped accepting proposals. (´･_･`)
@ScottDowne r?
=> Remove /add-session POST route

lib/helmet.jsx, package.json, pages/about.jsx, pages/contact.jsx, pages/expect.jsx, pages/guidelines.jsx, pages/home.jsx, pages/location.jsx, pages/tickets.jsx, pages/volunteer.jsx, public/index.html
=> Added meta description tags

pages/about.jsx
=> Removed call for proposals CTA from About

components/footer.jsx, components/header.jsx
=> Relocated What To Expect nav item

pages/volunteer.jsx
=> Copy changes to /volunteer

less/pages/tickets.less, less/pages/volunteer.less, pages/volunteer.jsx
=> Updated copy on /volunteer page

pages/pathways.jsx, pages/sessions.jsx
=> Copy changes on /sessions and /pathways

pages/guidelines.jsx
=> Added section to /guidelines

pages/fringe-events.jsx
changed date validation rule format; show events in sorted order (by time)
=> Fringe page tweaks

pages/sessions.jsx
As per https://github.com/mozilla/2015.mozillafestival.org/issues/320#issuecomment-151909867
Should be ok but still r? cc @mmmavis
=> Update 'Mozilla Learning Networks' text

less/pages/team.less, pages/team.jsx
=> Fixed #287 - fixed team page layout bug on safari

pages/sessions.jsx
r @mmmavis ?
Not sure about the branch
=> Adding Glabal Village twiiter handles - correction

pages/pathways.jsx
@mmmavis -- hope this helps, thanks!
=> Add Open Science Pathways

pages/pathways.jsx
As per https://github.com/mozilla/2015.mozillafestival.org/issues/340
=> Correcting smilies -> smileys

components/footer.jsx, components/header.jsx, less/pages/home.less
=> Add link to schedule

pages/home.jsx
As per https://github.com/MozillaFoundation/plan/issues/717#issuecomment-182025469
=> Clarify this is not 2016 dates

pages/contact.jsx
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/9
=> Updating contact page.

pages/home.jsx
For https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/4
=> Updating copy on landing page.

pages/location.jsx
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/6
=> Changing copy on location page

components/footer.jsx
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/10
=> Changing tweet value

pages/guidelines.jsx
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/15
=> Updating copy on Guidelines page

pages/expect.jsx
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/7
=> Moving sections around.

client.jsx, pages/submission-process.jsx
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/16
=> Updating routes to show submission-process. Updating copy.

pages/volunteer.jsx
For https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/11
=> Updating copy.

pages/about.jsx
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/13
=> Updating Mark's speech.

client.jsx, pages/sessions.jsx
For https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/48
=> Updating Routes. Adding `/spaces-and-sessions`

less/pages/tickets.less, pages/tickets.jsx
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/5
=> Adding Adult and Youth ticket descriptions

.travis.yml
=> Updated Heroku key in .travis.yml

app.js, pages/proposals.jsx
=> Added session title field to proposal form

app.js, lib/proposal-handler.js
=> related to #396 - add hatchet (for sending email confirmation)

pages/proposals.jsx, pages/sessions.jsx
=> Content changes

issue-template.md, lib/proposal-handler.js
=> Secondary space fix

lib/proposal-handler.js
=> Applied 'Stipend requested' label for 'travel-only' proposal tickets

.gitignore, less/components/header.less, less/index.less, less/pages/about.less, less/pages/expect.less, less/pages/fringe-events.less, less/pages/proposals.less, less/pages/remote.less, less/pages/team.less, less/pages/tickets.less, less/shared.less, less/variables.less
=> Added variables.less, some css cleanup

pages/proposals.jsx
=> Fixes mismatched space meta

pages/tickets.jsx
=> Added ticket prices on /tickets

pages/proposals.jsx
=> Changed 'Other facilitators' field to <textarea>

pages/sessions.jsx
=> Updated Fuel the Movement Space description

pages/guidelines.jsx
This fixes https://github.com/mozilla/mozillafestival.org/issues/431
=> Corecting the link to the submissions repo.

pages/proposals.jsx
I did not find much about inputcombo tag so I have added the regular link tag and to be opened in new page so you so not loose the page you are submitting. 
I am not sure if this is ok as we used the whole text as selection area before and now we reduce it to the radio button itself only. 
@autonome Is this a fix for #423 ? Would this work with the overall site @mmmavis?
=> Added the anchors for spaces to the proposal page

pages/expect.jsx
Closes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/78
=> Update “what to expect” page times

pages/guidelines.jsx
This fixes #442 reported by @spikeuk.
@mmmavis pls r?
=> Corrections according to #442

pages/tickets.jsx
Closes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/79
=> Add links to tickets after description paragraph

components/space-pathway-profile.jsx, pages/sessions.jsx
Closes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/85
=> Add links to space sessions

components/footer.jsx, pages/contact.jsx
Closes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/91
(I also changed a link deeper in the site to the proper location too)
=> Update medium link

components/footer.jsx
Closes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/92#issuecomment-246764206
=> Add links to terms and privacy policy

pages/home.jsx
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/101
=> Keep current 'buy a ticket' homepage CTA with updated copy

pages/team.jsx
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/109
=> Updated Dorine's bio

pages/team.jsx
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/113
=> Changed Luca's bio

less/pages/volunteer.less, pages/volunteer.jsx
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/112
@alanmoo tiny PR for you to review plz 😄
=> Updated volunteer page copy

pages/fringe-events.jsx
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/100
=> Fringe page copy tweaks

less/pages/expect.less, pages/expect.jsx
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/115#issuecomment-254206677
=> timeblock adjustment

components/header.jsx, less/pages/home.less
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/117
=> Added schedule link to nav

pages/team.jsx
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/119
=> Added tech girls link

components/space-pathway-profile.jsx, pages/sessions.jsx
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/118
=> spaces page updates

pages/sessions.jsx
Closes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/122#event-835373339
=> Add Michael Saunby to tale of two cities

components/header.jsx, components/speaker-tiny-card.jsx, pages/home.jsx, public/index.html
See https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/120
=> Post festival updates

components/header.jsx
=> Header link order update

pages/home.jsx
=> Speaker times

pages/expect.jsx
https://github.com/MozillaFoundation/Mozfest2016_production/issues/221
=> Add festival guide link

pages/fringe-events.jsx
This page wasn't pulling in google sheets properly with the upgrade, but since that functionality isn't needed right now I've just pulled in the pending changes from Hannah's PR to disable it.
=> Fix fringe page

pages/expect.jsx
=> Update what-to-expect video

pages/home.jsx
Somehow this one got prematurely checked off. #503
=> Update speaker section title and links

components/header.jsx, less/components/jumbotron.less
Some copying of other jumbotron styles though really this just needs to be cleaned up but it should work for now.
=> Fix mobile view of jumbotron

pages/home.jsx, pages/team.jsx
=> Text fixes

components/footer.jsx
Closes #491
@edrushka when do we want to go live with the changes about this year's festival? Whenever they're ready?
=> Do not merge yet: Update tweet intent url

less/components/header.less
=> Update nav link active/hover state to reflect new branding

components/footer.jsx
=> Cookies link

package.json, webpack.config.js
Minify webpack and use production version of react
=> Improve performance

public/index.html
content subject to copy review and styling.
fixes https://github.com/mozilla/mozillafestival.org/issues/565
=> ensure there is always content on the landing page

pages/proposals/form/fields.js, pages/proposals/proposals.jsx
=> Copy changes and added 2 more questions

components/footer.jsx
=> Updated sample tweet copy

less/pages/expect.less, pages/expect.jsx
=> 'What to expect' content changes

pages/proposals/form/fields.js, pages/proposals/proposals.jsx
=> Content tweaks to /proposals page

issue-template.md, lib/proposal-handler.js
=> Don't show Twitter handle on GitHub tickets

pages/expect.jsx, pages/spaces.jsx
=> Tiny copy fixes

pages/guidelines.jsx
=> /guidelines page changes

pages/projects.jsx
=> /projects page changes

pages/proposals/form/fields.js, pages/proposals/proposals.jsx
=> Proposal form changes

lib/proposal-handler.js
=> Proposal confirmation email

pages/proposals/proposals.jsx
=> 2nd space and additional lang bug

pages/spaces.jsx
=> Updated Decentralization wrangler list

pages/spaces.jsx
=> Updated Privacy & Security wrangler list

lib/proposal-handler.js
=> Updated secondary space github label

pages/proposals/proposals.jsx
=> Copy changes

components/footer.jsx
=> Fixes legal link

components/footer.jsx, less/components/footer.less
=> Added footer icons

README.md, lib/proposal-handler.js
=> Non-English proposal confirmation email

pages/proposals/language/english.json, pages/proposals/language/french.json, pages/proposals/language/german.json, pages/proposals/language/spanish.json, pages/proposals/proposals.jsx
=> Added more translations to proposal pages

pages/proposals/language/german.json
=> Fixes some German translations

pages/about.jsx
=> Updated Mark's speech bubble

issue-template.md, lib/proposal-handler.js
=> Show more proposal meta in GitHub ticket description

.gitignore, package-lock.json
Reverts mozilla/mozillafestival.org#667
=> Revert "Fix broken npm thing"

pages/volunteer.jsx
fixes #654 
@mmmavis - how's this? New commit without removing the package-lock.json file.
=> updates to volunteer page

pages/tickets.jsx
Fixes #674
Makes small copy change as per #674
=> copy change

pages/spaces.jsx
fixes #683 
Adds Artist Studio blurb, per #683
=> adds Artist Studio blurb

client.jsx, components/space-profile.jsx, pages/spaces.jsx
=> Scroll to anchor

client.jsx
=> Close CFP for gooood

components/member-profile.jsx, components/speaker-series-talk.jsx, less/components/index.less, pages/home.jsx, team-bio/experiences-wranglers.js
=> Updated a twitter handles. Added Twitter icon before all Twitter handles

pages/expect.jsx
=> Updated copy in a11y section

team-bio/production-members.js
=> Updated Sarah's bio

less/pages/guidelines.less, pages/guidelines.jsx
=> Updated participation guideline

pages/expect.jsx
=> Updated Sat's party time

components/header.jsx, less/components/header.less, less/components/jumbotron.less, less/pages/home.less, pages/home.jsx
=> Updated links plus some styling tweaks 

pages/expect.jsx
=> Updated festival guide link

components/header.jsx, pages/home.jsx
=> Update header, tickets

team-bio/space-wranglers.js
Reverts mozilla/mozillafestival.org#759, unsure about privacy concerns
=> Revert "Adding twitter handles"

app.js, package-lock.json, package.json
=> Migrated to express v4

package-lock.json, package.json, pages/location.jsx
=> Migrated mustache.js to v2.2.1 and fixed broken map on /location page

app.js, package-lock.json, package.json
=> Removed 'request' since it's not being used anywhere

package-lock.json, package.json
=> Updated 'uuid'

package-lock.json, package.json
=> Updated 'mofo-bootstrap' and 'mofo-ui'

package-lock.json, package.json
=> Updated 'webpack'

package-lock.json, package.json, pages/fringe-events/form/fields.js
=> Updated 'autoprefixer', 'express-rate-limit', 'slugify' and removed 'react-select'

package-lock.json, package.json
=> Updated 'react-datepicker', 'chokidar', 'eslint', and 'eslint-plugin-react'

lib/helmet.jsx, package-lock.json, package.json, pages/about.jsx, pages/cfp-closed.jsx, pages/contact.jsx, pages/expect.jsx, pages/guidelines.jsx, pages/home.jsx, pages/location.jsx, pages/media.jsx, pages/remote.jsx, pages/tickets.jsx, pages/volunteer.jsx, server.js
=> Upgrade react-helmet, fixed things so <meta> gets properly updated

pages/home.jsx
=> Updated home page CTA

components/header.jsx
Fixes https://github.com/mozilla/mozillafestival.org/issues/815
=> Changes to nav items.

components/sponsors.jsx
Fixes https://github.com/mozilla/mozillafestival.org/issues/827
=> New sponsors page for 2018 updates

components/footer.jsx
Fixes: https://github.com/mozilla/mozillafestival.org/issues/824
=> update tweet text

pages/media.jsx
Fixes https://github.com/mozilla/mozillafestival.org/issues/823
=> Updating media page

pages/house.jsx
Just the second last checkbox in this ticket https://github.com/mozilla/mozillafestival.org/issues/819
=> Small update to house page.

pages/expect.jsx
Fixes part of:
https://github.com/mozilla/mozillafestival.org/issues/821
and I think also this?
https://github.com/mozilla/mozillafestival.org/issues/816
=> Updating vimeo video for expects page.

less/shared.less, pages/home.jsx
Fixes https://github.com/mozilla/mozillafestival.org/issues/816
=> Finished home page

pages/home.jsx
=> Clarify Dialogues and Debates are last year

pages/house.jsx
=> Fixed typo

pages/house.jsx
=> Fixed another typo

pages/guidelines.jsx
=> Updated /guidelines page

lib/proposal-handler.js, pages/proposals/form/fields.js, pages/proposals/proposals.jsx, proposal-ticket-template.md
=> CFP - changed the 'l10languages' field to multiple choices question

pages/proposals/form/fields.js, pages/proposals/language/english.json
=> Fixed typo portugese -> portuguese

components/jumbotron.jsx, components/nav-bar.jsx, less/components/index.less, less/components/jumbotron.less, less/components/nav-bar.less, less/pages/expect.less, less/pages/home.less, main.jsx, pages/home.jsx, pages/house.jsx
Related to #910 
https://mozillafestival-org-sta-pr-919.herokuapp.com/
=> Cleaned up header.jsx code so it's not using absolute positioning

pages/house.jsx
=> Removed 2017 House Events from /house page

team-bio/experiences-wranglers.js, team-bio/space-wranglers.js
=> Added wranglers bio & updated list of wranglers

components/loading-notice.jsx, less/components/index.less, less/components/loading-notice.less, less/shared.less, pages/fringe-events/fringe-events.jsx, pages/house.jsx
=> House page - better system messages for the events section

less/pages/fringe-events.less, pages/fringe-events/form/fields.js, pages/fringe-events/fringe-events.jsx
=> Updated content on /fringe page

lib/helmet.jsx, main.jsx, pages/about.jsx, pages/expect.jsx, pages/home.jsx
=> Updated site's description & fixed some <meta> not being correctly set issues

main.jsx
=> /late-proposals page

main.jsx, pages/cfp-closed.jsx
=> Updated /proposals page to show its CFP close state

lib/proposal-handler.js
Related to #1036
https://www.npmjs.com/package/request#super-simple-to-use
I reused the working code snippet from last year but there were. probably some breaking changes that I wasn't aware of when I updated `request` npm package.
=> Fixed crash bug caused by reading property of undefined

pages/home.jsx
=> Updated tickets cta link

components/footer.jsx
=> Open twitter link in new tab

components/nav-bar.jsx, server.js
Related to #1065 - add 'fringe' to nav bar
Related to #806 - updated GA UA code to our new GA property's UA code
=> Nav bar and GA code

pages/spaces.jsx
=> Added gaming mozfest description

pages/home.jsx, pages/house.jsx
- Related to #1086 - made festival locations clearer
- Related to #1101 - updated location link on /house page
=> Various site updates

pages/house.jsx, server.js
=> Started showing public House events on /house page

pages/about.jsx
=> About page hero - added button that links to 2018 festival guide

talks/2018.js
=> Updated a speaker's bio

less/components/notification-bar.less, pages/about.jsx
=> Added notification bar to /about page

less/pages/tickets.less, pages/tickets.jsx
=> Labelling sold out tickets

server.js
cc @mmmavis to make sure you're ok with this.
Added this per https://github.com/MozillaFoundation/mofo-devops/issues/623#issuecomment-430667951
=> Add caching for static assets

talks/2018.js
=> D&D - added links to YouTube

package.json
Update package.json so that Heroku doesn't run the build script.
=> Update package.json: Heroku build change

package.json
We don't need that flag anymore.
ref https://github.com/MozillaFoundation/mofo-devops-private/issues/208
=> remove outdated flag
